version: '3'
services:
  # Spring Boot Backend Service
  azure-frontend:
    image: h3registry.azurecr.io/front-app-react
    container_name: azure-frontend
    ports:
      - "3000:3000"
    depends_on:
      - azure-backend
  # React Frontend Service
  azure-backend:
    image: h3registry.azurecr.io/back-app-spring
    container_name: azure-backend
    ports:
      - "9191:9191"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://springdb1.database.windows.net:1433;database=springAppDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"
      SPRING_DATASOURCE_USERNAME: "CloudSA5de17cad"
      SPRING_DATASOURCE_PASSWORD: "Password@123"
    restart: always
    depends_on:
      - azure-sql
  # Azure SQL Database
  azure-sql:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_USERNAME: "CloudSA5de17cad"
      SA_PASSWORD: "Password@123"
    ports:
      - "1433:1433"

